type ConcertProps = {
  name: string;
  date: string;
  time: string;
  place: string;
  city: string;
  img: string;
  festival?: 'Lollapalooza' | 'Mästerbotten';
};

const concerts = [
  {
    name: 'Benjamin Ingrosso',
    date: '2024-08-09',
    time: '21:00',
    place: 'Stadion',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Benjamin_Ingrosso_Lollapalooza_2022_Stockholm_%28cropped%29.jpg/1280px-Benjamin_Ingrosso_Lollapalooza_2022_Stockholm_%28cropped%29.jpg',
  },
  {
    name: 'Hooja',
    date: '2024-07-25',
    time: '20:00',
    place: 'Dalhalla',
    city: 'Rättvik',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/89/Hoojaa.png',
  },
  {
    name: 'Bruce Springsteen',
    date: '2024-07-15',
    time: '20:00',
    place: 'Strawberry Arena',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Bruce_Springsteen_-_Roskilde_Festival_2012.jpg/800px-Bruce_Springsteen_-_Roskilde_Festival_2012.jpg',
  },
  {
    name: 'The Hives',
    date: '2024-07-06',
    time: '20:00',
    place: 'Gärdet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Deichbrand2018-TheHives-58.jpg/1280px-Deichbrand2018-TheHives-58.jpg',
  },
  {
    name: 'Toto',
    date: '2024-07-05',
    time: '20:00',
    place: 'Gärdet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/TOTO_live_2010_in_Copenhagen_in_KB_Hallen.JPG/1280px-TOTO_live_2010_in_Copenhagen_in_KB_Hallen.JPG',
  },
  {
    name: 'Bring me the Horizon',
    date: '2024-07-01',
    time: '20:00',
    place: 'Gärdet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/2023_Rock_im_Park_-_Bring_Me_The_Horizon_-_by_2eight_-_7DS4804.jpg/1280px-2023_Rock_im_Park_-_Bring_Me_The_Horizon_-_by_2eight_-_7DS4804.jpg',
  },
  {
    name: 'The Offspring',
    date: '2024-06-18',
    time: '20:00',
    place: 'Gröna Lund',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/The_Offspring_2024.jpg/1280px-The_Offspring_2024.jpg',
  },
  {
    name: 'Infected Mushroom',
    date: '2023-02-25',
    time: '20:00',
    place: 'Annexet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/61/Infected_Mushroom_in_Russia.jpg',
  },
  {
    name: 'Dermot Kennedy',
    date: '2023-03-11',
    time: '19:00',
    place: 'Annexet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Dermot_Kennedy_performing_at_2019_Lowlands_Festival.png',
  },
  {
    name: 'Michael Bublé',
    date: '2023-03-10',
    time: '20:00',
    place: 'Globen',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/2/28/Michael_Buble_by_Gage_Skidmore_%28cropped%29.jpg',
  },
  {
    name: 'Loreen',
    date: '2023-03-11',
    time: '22:00',
    place: 'Berns',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/1/17/Loreen_-_Melodifestivalen_2023%2C_Malm%C3%B6_118_%28cropped%29.jpg',
  },
  {
    name: 'Nordman',
    date: '2023-03-11',
    time: '22:00',
    place: 'Berns',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/7/72/Nordman_2013-10-04_001.jpg',
  },
  {
    name: 'Panetoz',
    date: '2023-03-11',
    time: '23:00',
    place: 'Berns',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/c2/Panetoz-Mama_Africa_videoshoot.jpg',
  },
  {
    name: 'Roger Waters',
    date: '2023-04-15',
    time: '19:00',
    place: 'Tele 2 Arena',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/5/50/Roger_Waters_Newport_Folk_Festival_2015.jpg',
  },
  {
    name: 'Post Malone',
    date: '2023-04-26',
    time: '19:30',
    place: 'Avicii Arena',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Post_Malone_July_2021_%28cropped%29.jpg',
  },
  {
    name: 'Wutang Clan',
    date: '2023-06-02',
    time: '20:00',
    place: 'Avicii Arena',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/80/Wu_Tang_Clan_on_Stage.jpg',
  },
  {
    name: 'Nas',
    date: '2023-06-02',
    time: '20:00',
    place: 'Avicii Arena',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Nas-01-mika.jpg',
  },
  {
    name: 'Jelassi',
    date: '2023-04-26',
    time: '22:00',
    place: 'Slakthusområdet',
    festival: 'Mästerbotten',
    city: 'Stockholm',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9ETRyM5yTFchMaWbkfvqv_CpTyJnFpv0kwQ&s',
  },
  {
    name: 'Broder John',
    date: '2023-04-26',
    time: '23:00',
    place: 'Slakthusområdet',
    festival: 'Mästerbotten',
    city: 'Stockholm',
    img: 'https://static-cdn.sr.se/images/4323/1a65710c-6f31-4188-acf5-1c52676ed0f6.jpg',
  },
  {
    name: 'Hoopdiggas Club',
    date: '2023-04-26',
    time: '23:00',
    place: 'Slakthusområdet',
    festival: 'Mästerbotten',
    city: 'Stockholm',
    img: 'https://mnd-assets.mynewsdesk.com/image/upload/ar_16:9,c_fill,dpr_auto,f_auto,g_sm,q_auto:good,w_746/n5kgtniloeqr54fakljh',
  },
  {
    name: 'Cleo',
    date: '2023-04-26',
    time: '23:30',
    place: 'Slakthusområdet',
    festival: 'Mästerbotten',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Valborg_Cleo_0785_120430_MPN_Original.jpg',
  },
  {
    name: 'Trainspotters',
    date: '2023-04-26',
    time: '00:30',
    place: 'Slakthusområdet',
    festival: 'Mästerbotten',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Trainspotters-Live_At_Umea_Jazz_Festival-Photo_by_Jonatan_Nylander.jpg',
  },
  {
    name: 'Fridlyst',
    date: '2023-04-26',
    time: '00:30',
    place: 'Slakthusområdet',
    festival: 'Mästerbotten',
    city: 'Stockholm',
    img: 'https://wp.dopest.se/wp-content/uploads/2020/05/fridlyst-800x450.jpg',
  },
  {
    name: 'Dean Lewis',
    date: '2023-06-30',
    time: '19:15',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/3/38/Dean_Lewis-7561.jpg',
  },
  {
    name: 'Thomas Stenström',
    date: '2023-06-30',
    time: '20:15',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Thomas_Stenstr%C3%B6m_%281%29_By_Daniel_%C3%85hs_Karlsson_%28cropped%29.jpg',
  },
  {
    name: 'Zara Larsson',
    date: '2023-06-30',
    time: '21:15',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/62/Zara_Larsson_-_Ilosaarirock_2018_-_17.jpg',
  },
  {
    name: 'Marcus Mumford',
    date: '2023-06-30',
    time: '21:30',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/2/2a/Marcus_Mumford_at_Newport_Folk_Festival_2018_by_Sachyn_Mital.jpg',
  },
  {
    name: 'Afrojack',
    date: '2023-06-30',
    time: '22:45',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/5/53/Afrojack_2015.jpg',
  },
  {
    name: 'Kygo',
    date: '2023-06-31',
    time: '??',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Kygo_%2828481718120%29_%282%29.jpg',
  },
  {
    name: 'Lil Nas',
    date: '2023-06-31',
    time: '??',
    place: 'Gärder',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/8a/Lil_Nas_X_Talks_About_Gaining_His_Father%27s_Acceptance%2C_Growing_Up_in_Atlanta%2C_%26_FINDING_HIMSELF_7-32_screenshot_%28headshot%29.jpg',
  },
  {
    name: 'Fatboy Slim',
    date: '2023-06-31',
    time: '??',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/4/43/Fatboy_Slim%2C_Iris_Festival_2025.jpg',
  },
  {
    name: 'Sofi Tukker',
    date: '2023-06-31',
    time: '??',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/9/91/Sofi_Tukker_06_04_2016_-14_%2827454016316%29_%28cropped%29.jpg',
  },
  {
    name: 'Iann Dior',
    date: '2023-06-31',
    time: '??',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://dynamicmedia.livenationinternational.com/Media/q/p/j/f9712910-1258-4048-8ec6-8e0b2fca3e55.jpg',
  },
  {
    name: 'Mumford and Sons',
    date: '2023-07-01',
    time: '??',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Mumford_%26_Sons%2C_performing_at_Aviemore%2C_Scotland_2015.jpg',
  },
  {
    name: 'Olivia Lobato',
    date: '2023-07-01',
    time: '??',
    place: 'Slotsskogen',
    festival: 'Way Out West',
    city: 'Göteborg',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/8b/Olivia_Lobato_Rockbj%C3%B6rnen_2024_%2854%29_%28cropped%29.jpg',
  },
  {
    name: 'Aurora',
    date: '2023-08-10',
    time: '??',
    place: 'Slotsskogen',
    festival: 'Way Out West',
    city: 'Göteborg',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/65/AURORA%2C_Ravnedalen_Live_festival%2C_Kristiansand%2C_Norway_%2853867200364%29_%28cropped%29.jpg',
  },
  {
    name: 'Tove Lo',
    date: '2023-07-11',
    time: '??',
    place: 'Slotsskogen',
    festival: 'Way Out West',
    city: 'Göteborg',
    img: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Tove_Lo_%282%29_By_Daniel_%C3%85hs_Karlsson.jpeg',
  },
  {
    name: 'Blur',
    date: '2023-07-11',
    time: '??',
    place: 'Slotsskogen',
    festival: 'Way Out West',
    city: 'Göteborg',
    img: 'https://upload.wikimedia.org/wikipedia/commons/1/1f/BlurWembley090723_%28166_of_172%29_colour_change_%28shorter_crop%29.jpg',
  },
  {
    name: 'Tenacious D',
    date: '2024-04-29',
    time: '19.00',
    place: 'Hovet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Tenacious_D_-_Rock_am_Ring_2016_-2016155215305_2016-06-03_Rock_am_Ring_-_Sven_-_1D_X_MK_II_-_0802_-_AK8I0813_mod.jpg/2880px-Tenacious_D_-_Rock_am_Ring_2016_-2016155215305_2016-06-03_Rock_am_Ring_-_Sven_-_1D_X_MK_II_-_0802_-_AK8I0813_mod.jpg',
  },
  {
    name: 'Ghost',
    date: '2025-04-29',
    time: '19.00',
    place: 'Göransson Arena',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/c7/Ghost_Rockavaria_2016_%2814_von_14%29.jpg',
  },
  {
    name: 'Iron Maiden',
    date: '2025-04-29',
    time: '19.00',
    place: 'Tele 2 Arena',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Iron_Maiden_47f_b.jpg',
  },
  {
    name: 'Millencollin',
    date: '2025-06-24',
    time: '16.30',
    place: 'Hovet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/9/9e/Millencolin-2008.jpg',
  },
  {
    name: 'Weezer',
    date: '2025-06-24',
    time: '17.30',
    place: 'Hovet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/f/f6/Weezer_Bethlehem_2019_1.jpg',
  },
  {
    name: 'Green day',
    date: '2025-06-24',
    time: '19.00',
    place: 'Hovet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Green_Day_-_2022154231209_2022-06-03_Rock_am_Ring_-_Sven_-_1D_X_MK_II_-_3537_-_B70I8091.jpg',
  },
  {
    name: `Guns N' Roses`,
    date: '2025-07-09',
    time: '19.00',
    place: 'Strawberry Arena',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/68/Guns_n_Roses_Nottingham_2012.JPG',
  },
  {
    name: 'Kendrick Lamar',
    date: '2025-08-09',
    time: '19.00',
    place: 'Tele 2 Arena',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/7/76/Kendrick_Lamar_2018_Pulitzer_Prize_ceremony_%283x4_cropped%29.jpg',
  },
];

export { concerts };
export type { ConcertProps };
