type ConcertProps = {
  name: string;
  date: string;
  time: string;
  place: string;
  city: string;
  img: string;
  festival?: 'Lollapalooza' | 'Mästerbotten';
};

const concerts = [
  {
    name: 'Hooja',
    date: '2024-07-25',
    time: '20:00',
    place: 'Dalhalla',
    city: 'Rättvik',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/89/Hoojaa.png',
  },
  {
    name: 'The Hives',
    date: '2024-07-06',
    time: '20:00',
    place: 'Gärdet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Deichbrand2018-TheHives-58.jpg/1280px-Deichbrand2018-TheHives-58.jpg',
  },
  {
    name: 'Toto',
    date: '2024-07-05',
    time: '20:00',
    place: 'Gärdet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/TOTO_live_2010_in_Copenhagen_in_KB_Hallen.JPG/1280px-TOTO_live_2010_in_Copenhagen_in_KB_Hallen.JPG',
  },
  {
    name: 'Bring me the Horizon',
    date: '2024-07-01',
    time: '20:00',
    place: 'Gärdet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/2023_Rock_im_Park_-_Bring_Me_The_Horizon_-_by_2eight_-_7DS4804.jpg/1280px-2023_Rock_im_Park_-_Bring_Me_The_Horizon_-_by_2eight_-_7DS4804.jpg',
  },
  {
    name: 'The Offspring',
    date: '2024-06-18',
    time: '20:00',
    place: 'Gröna Lund',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/The_Offspring_2024.jpg/1280px-The_Offspring_2024.jpg',
  },
  {
    name: 'Infected Mushroom',
    date: '2023-02-25',
    time: '20:00',
    place: 'Annexet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/61/Infected_Mushroom_in_Russia.jpg',
  },
  {
    name: 'Dermot Kennedy',
    date: '2023-03-11',
    time: '19:00',
    place: 'Annexet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Dermot_Kennedy_performing_at_2019_Lowlands_Festival.png',
  },
  {
    name: 'Michael Bublé',
    date: '2023-03-10',
    time: '20:00',
    place: 'Globen',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/0/0c/MichaelBubleDanceFeb2011.jpg',
  },
  {
    name: 'Loreen',
    date: '2023-03-11',
    time: '22:00',
    place: 'Berns',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/1/17/Loreen_-_Melodifestivalen_2023%2C_Malm%C3%B6_118_%28cropped%29.jpg',
  },
  {
    name: 'Nordman',
    date: '2023-03-11',
    time: '22:00',
    place: 'Berns',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/7/72/Nordman_2013-10-04_001.jpg',
  },
  {
    name: 'Panetoz',
    date: '2023-03-11',
    time: '23:00',
    place: 'Berns',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/8e/Panetoz_p%C3%A5_presentationen_Mello_2023_Link%C3%B6ping_1.jpg',
  },
  {
    name: 'Roger Waters',
    date: '2023-04-15',
    time: '19:00',
    place: 'Tele 2 Arena',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/5/50/Roger_Waters_Newport_Folk_Festival_2015.jpg',
  },
  {
    name: 'Post Malone',
    date: '2023-04-26',
    time: '19:30',
    place: 'Avicii Arena',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/6/63/CHRISALLMEID_CHRISALLMEID_POSTMALONE-3.jpg',
  },
  {
    name: 'Wutang Clan',
    date: '2023-06-02',
    time: '20:00',
    place: 'Avicii Arena',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/8/80/Wu_Tang_Clan_on_Stage.jpg',
  },
  {
    name: 'Nas',
    date: '2023-06-02',
    time: '20:00',
    place: 'Avicii Arena',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Nas-01-mika.jpg',
  },
  {
    name: 'Jelassi',
    date: '2023-04-26',
    time: '22:00',
    place: 'Slakthusområdet',
    festival: 'Mästerbotten',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Punctus_interrogativus_from_Bern%2C_B%C3%BCrgerbibliothek_Cod._162%2C_f._15r.jpg',
  },
  {
    name: 'Broder John',
    date: '2023-04-26',
    time: '23:00',
    place: 'Slakthusområdet',
    festival: 'Mästerbotten',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Punctus_interrogativus_from_Bern%2C_B%C3%BCrgerbibliothek_Cod._162%2C_f._15r.jpg',
  },
  {
    name: 'Hoopdiggas Club',
    date: '2023-04-26',
    time: '23:00',
    place: 'Slakthusområdet',
    festival: 'Mästerbotten',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Punctus_interrogativus_from_Bern%2C_B%C3%BCrgerbibliothek_Cod._162%2C_f._15r.jpg',
  },
  {
    name: 'Cleo',
    date: '2023-04-26',
    time: '23:30',
    place: 'Slakthusområdet',
    festival: 'Mästerbotten',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Valborg_Cleo_0785_120430_MPN_Original.jpg',
  },
  {
    name: 'Trainspotters',
    date: '2023-04-26',
    time: '00:30',
    place: 'Slakthusområdet',
    festival: 'Mästerbotten',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Trainspotters-Live_At_Umea_Jazz_Festival-Photo_by_Jonatan_Nylander.jpg',
  },
  {
    name: 'Fridlyst',
    date: '2023-04-26',
    time: '00:30',
    place: 'Slakthusområdet',
    festival: 'Mästerbotten',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Punctus_interrogativus_from_Bern%2C_B%C3%BCrgerbibliothek_Cod._162%2C_f._15r.jpg',
  },
  {
    name: 'Dean Lewis',
    date: '2023-06-30',
    time: '19:15',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Punctus_interrogativus_from_Bern%2C_B%C3%BCrgerbibliothek_Cod._162%2C_f._15r.jpg',
  },
  {
    name: 'Thomas Stenström',
    date: '2023-06-30',
    time: '20:15',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Punctus_interrogativus_from_Bern%2C_B%C3%BCrgerbibliothek_Cod._162%2C_f._15r.jpg',
  },
  {
    name: 'Zara Larsson',
    date: '2023-06-30',
    time: '21:15',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Punctus_interrogativus_from_Bern%2C_B%C3%BCrgerbibliothek_Cod._162%2C_f._15r.jpg',
  },
  {
    name: 'Marcus Mumford',
    date: '2023-06-30',
    time: '21:30',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Punctus_interrogativus_from_Bern%2C_B%C3%BCrgerbibliothek_Cod._162%2C_f._15r.jpg',
  },
  {
    name: 'Afrojack',
    date: '2023-06-30',
    time: '22:45',
    place: 'Gärdet',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Punctus_interrogativus_from_Bern%2C_B%C3%BCrgerbibliothek_Cod._162%2C_f._15r.jpg',
  },
  {
    name: 'Kygo',
    date: '2023-06-31',
    time: '??',
    place: 'Stockholm',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/d/dd/Kygo_%2828481718120%29_%282%29.jpg',
  },
  {
    name: 'Lil Nas',
    date: '2023-06-31',
    time: '??',
    place: 'Stockholm',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://sv.wikipedia.org/wiki/Lil_Nas_X#/media/Fil:Glasto2023_(348_of_468)_(53009419903)_(cropped).jpg',
  },
  {
    name: 'Fatboy Slim',
    date: '2023-06-31',
    time: '??',
    place: 'Stockholm',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://sv.wikipedia.org/wiki/Fatboy_Slim#/media/Fil:Fatboy_Slim_in_2004.jpg',
  },
  {
    name: 'Sofi Tukker',
    date: '2023-06-31',
    time: '??',
    place: 'Stockholm',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: '',
  },
  {
    name: 'Iann Dior',
    date: '2023-06-31',
    time: '??',
    place: 'Stockholm',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: '',
  },
  {
    name: 'Mumford and Sons',
    date: '2023-07-01',
    time: '??',
    place: 'Stockholm',
    festival: 'Lollapalooza',
    city: 'Stockholm',
    img: 'https://sv.wikipedia.org/wiki/Mumford_%26_Sons#/media/Fil:MS2015.jpg',
  },
  {
    name: 'Olivia Lobato',
    date: '2023-07-01',
    time: '??',
    place: 'Stockholm',
    festival: 'Way Out West',
    city: 'Stockholm',
    img: 'https://sv.wikipedia.org/wiki/Olivia_Lobato#/media/Fil:Olivia_Lobato_Mix_Megapol_concert.jpg',
  },
  {
    name: 'Aurora',
    date: '2023-08-10',
    time: '??',
    place: 'Stockholm',
    festival: 'Way Out West',
    city: 'Stockholm',
    img: 'https://sv.wikipedia.org/wiki/Aurora_Aksnes#/media/Fil:Aurora_Stavernfestivalen_2018_(192156).jpg',
  },
  {
    name: 'Tove Lo',
    date: '2023-07-11',
    time: '??',
    place: 'Stockholm',
    festival: 'Way Out West',
    city: 'Stockholm',
    img: 'https://sv.wikipedia.org/wiki/Tove_Lo#/media/Fil:Tove_Lo_at_Lollapalooza_Chicago_2017.jpg',
  },
  {
    name: 'Blur',
    date: '2023-07-11',
    time: '??',
    place: 'Stockholm',
    festival: 'Way Out West',
    city: 'Stockholm',
    img: 'https://sv.wikipedia.org/wiki/Blur#/media/Fil:Blur_live_29.07.2013_in_Rome.jpg',
  },
  {
    name: 'Tenacious D',
    date: '2024-04-29',
    time: '19.00',
    place: 'Hovet',
    city: 'Stockholm',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Tenacious_D_-_Rock_am_Ring_2016_-2016155215305_2016-06-03_Rock_am_Ring_-_Sven_-_1D_X_MK_II_-_0802_-_AK8I0813_mod.jpg/2880px-Tenacious_D_-_Rock_am_Ring_2016_-2016155215305_2016-06-03_Rock_am_Ring_-_Sven_-_1D_X_MK_II_-_0802_-_AK8I0813_mod.jpg',
  },
];

const upcomingConcerts = [];

export { upcomingConcerts, concerts };
export type { ConcertProps };
