export const players = [
  // {
  //   name: "Joakim Örtbrant",
  //   handicap: 25,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 8 },
  //         { id: "2", label: "2", score: 9 },
  //         { id: "3", label: "3", score: 7 },
  //         { id: "4", label: "4", score: 5 },
  //         { id: "5", label: "5", score: 3 },
  //         { id: "6", label: "6", score: 7 },
  //         { id: "7", label: "7", score: 6 },
  //         { id: "8", label: "8", score: 6 },
  //         { id: "9", label: "9", score: 5 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 6 },
  //         { id: "11", label: "11", score: 4 },
  //         { id: "12", label: "12", score: 5 },
  //         { id: "13", label: "13", score: 7 },
  //         { id: "14", label: "14", score: 4 },
  //         { id: "15", label: "15", score: 6 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Emil Ekberg",
  //   handicap: 11,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 7 },
  //         { id: "2", label: "2", score: 4 },
  //         { id: "3", label: "3", score: 5 },
  //         { id: "4", label: "4", score: 4 },
  //         { id: "5", label: "5", score: 4 },
  //         { id: "6", label: "6", score: 7 },
  //         { id: "7", label: "7", score: 3 },
  //         { id: "8", label: "8", score: 5 },
  //         { id: "9", label: "9", score: 5 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Jonas Westman",
  //   handicap: 13,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 5 },
  //         { id: "2", label: "2", score: 7 },
  //         { id: "3", label: "3", score: 4 },
  //         { id: "4", label: "4", score: 3 },
  //         { id: "5", label: "5", score: 5 },
  //         { id: "6", label: "6", score: 6 },
  //         { id: "7", label: "7", score: 5 },
  //         { id: "8", label: "8", score: 6 },
  //         { id: "9", label: "9", score: 5 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Christian Ranebäck",
  //   handicap: 22,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 7 },
  //         { id: "2", label: "2", score: 5 },
  //         { id: "3", label: "3", score: 4 },
  //         { id: "4", label: "4", score: 6 },
  //         { id: "5", label: "5", score: 5 },
  //         { id: "6", label: "6", score: 4 },
  //         { id: "7", label: "7", score: 6 },
  //         { id: "8", label: "8", score: 10 },
  //         { id: "9", label: "9", score: 4 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Anders Uhlin",
  //   handicap: 22,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 7 },
  //         { id: "2", label: "2", score: 5 },
  //         { id: "3", label: "3", score: 5 },
  //         { id: "4", label: "4", score: 6 },
  //         { id: "5", label: "5", score: 5 },
  //         { id: "6", label: "6", score: 7 },
  //         { id: "7", label: "7", score: 6 },
  //         { id: "8", label: "8", score: 7 },
  //         { id: "9", label: "9", score: 3 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Sam Kyller",
  //   handicap: 10,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 5 },
  //         { id: "2", label: "2", score: 4 },
  //         { id: "3", label: "3", score: 5 },
  //         { id: "4", label: "4", score: 5 },
  //         { id: "5", label: "5", score: 3 },
  //         { id: "6", label: "6", score: 5 },
  //         { id: "7", label: "7", score: 5 },
  //         { id: "8", label: "8", score: 5 },
  //         { id: "9", label: "9", score: 3 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Erik Hellqvist",
  //   handicap: 32,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 8 },
  //         { id: "2", label: "2", score: 6 },
  //         { id: "3", label: "3", score: 5 },
  //         { id: "4", label: "4", score: 7 },
  //         { id: "5", label: "5", score: 5 },
  //         { id: "6", label: "6", score: 7 },
  //         { id: "7", label: "7", score: 5 },
  //         { id: "8", label: "8", score: 6 },
  //         { id: "9", label: "9", score: 4 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Hjalmar Woods Sköldefors",
  //   handicap: 34,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 7 },
  //         { id: "2", label: "2", score: 6 },
  //         { id: "3", label: "3", score: 4 },
  //         { id: "4", label: "4", score: 8 },
  //         { id: "5", label: "5", score: 4 },
  //         { id: "6", label: "6", score: 7 },
  //         { id: "7", label: "7", score: 5 },
  //         { id: "8", label: "8", score: 7 },
  //         { id: "9", label: "9", score: 5 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Oskar Kallenbach",
  //   handicap: 26,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 7 },
  //         { id: "2", label: "2", score: 6 },
  //         { id: "3", label: "3", score: 5 },
  //         { id: "4", label: "4", score: 6 },
  //         { id: "5", label: "5", score: 4 },
  //         { id: "6", label: "6", score: 6 },
  //         { id: "7", label: "7", score: 9 },
  //         { id: "8", label: "8", score: 8 },
  //         { id: "9", label: "9", score: 6 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Hans Hall",
  //   handicap: 17,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 5 },
  //         { id: "2", label: "2", score: 5 },
  //         { id: "3", label: "3", score: 4 },
  //         { id: "4", label: "4", score: 6 },
  //         { id: "5", label: "5", score: 4 },
  //         { id: "6", label: "6", score: 5 },
  //         { id: "7", label: "7", score: 4 },
  //         { id: "8", label: "8", score: 7 },
  //         { id: "9", label: "9", score: 4 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Erik Unander-Scharin",
  //   handicap: 11,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 5 },
  //         { id: "2", label: "2", score: 5 },
  //         { id: "3", label: "3", score: 5 },
  //         { id: "4", label: "4", score: 4 },
  //         { id: "5", label: "5", score: 3 },
  //         { id: "6", label: "6", score: 6 },
  //         { id: "7", label: "7", score: 7 },
  //         { id: "8", label: "8", score: 6 },
  //         { id: "9", label: "9", score: 5 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Henrik Svensson",
  //   handicap: 11,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 8 },
  //         { id: "2", label: "2", score: 7 },
  //         { id: "3", label: "3", score: 4 },
  //         { id: "4", label: "4", score: 6 },
  //         { id: "5", label: "5", score: 3 },
  //         { id: "6", label: "6", score: 4 },
  //         { id: "7", label: "7", score: 5 },
  //         { id: "8", label: "8", score: 5 },
  //         { id: "9", label: "9", score: 3 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Johan Lidén",
  //   handicap: 53,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 10 },
  //         { id: "2", label: "2", score: 6 },
  //         { id: "3", label: "3", score: 7 },
  //         { id: "4", label: "4", score: 8 },
  //         { id: "5", label: "5", score: 7 },
  //         { id: "6", label: "6", score: 8 },
  //         { id: "7", label: "7", score: 7 },
  //         { id: "8", label: "8", score: 8 },
  //         { id: "9", label: "9", score: 6 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Filip Wirefors",
  //   handicap: 7,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 6 },
  //         { id: "2", label: "2", score: 4 },
  //         { id: "3", label: "3", score: 5 },
  //         { id: "4", label: "4", score: 4 },
  //         { id: "5", label: "5", score: 5 },
  //         { id: "6", label: "6", score: 4 },
  //         { id: "7", label: "7", score: 4 },
  //         { id: "8", label: "8", score: 5 },
  //         { id: "9", label: "9", score: 5 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "David Piehl",
  //   handicap: 21,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 8 },
  //         { id: "2", label: "2", score: 5 },
  //         { id: "3", label: "3", score: 5 },
  //         { id: "4", label: "4", score: 6 },
  //         { id: "5", label: "5", score: 3 },
  //         { id: "6", label: "6", score: 5 },
  //         { id: "7", label: "7", score: 5 },
  //         { id: "8", label: "8", score: 5 },
  //         { id: "9", label: "9", score: 5 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Kristoffer Cassel",
  //   handicap: 22,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 5 },
  //         { id: "2", label: "2", score: 5 },
  //         { id: "3", label: "3", score: 5 },
  //         { id: "4", label: "4", score: 4 },
  //         { id: "5", label: "5", score: 3 },
  //         { id: "6", label: "6", score: 6 },
  //         { id: "7", label: "7", score: 5 },
  //         { id: "8", label: "8", score: 7 },
  //         { id: "9", label: "9", score: 5 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
  // {
  //   name: "Wulf Hambach",
  //   handicap: 24,
  //   result: 0,
  //   scoreCard: {
  //     out: {
  //       holes: [
  //         { id: "1", label: "1", score: 6 },
  //         { id: "2", label: "2", score: 6 },
  //         { id: "3", label: "3", score: 6 },
  //         { id: "4", label: "4", score: 6 },
  //         { id: "5", label: "5", score: 4 },
  //         { id: "6", label: "6", score: 6 },
  //         { id: "7", label: "7", score: 6 },
  //         { id: "8", label: "8", score: 6 },
  //         { id: "9", label: "9", score: 4 },
  //       ],
  //       total: 0,
  //     },
  //     in: {
  //       holes: [
  //         { id: "10", label: "10", score: 0 },
  //         { id: "11", label: "11", score: 0 },
  //         { id: "12", label: "12", score: 0 },
  //         { id: "13", label: "13", score: 0 },
  //         { id: "14", label: "14", score: 0 },
  //         { id: "15", label: "15", score: 0 },
  //         { id: "16", label: "16", score: 0 },
  //         { id: "17", label: "17", score: 0 },
  //         { id: "18", label: "18", score: 0 },
  //       ],
  //       total: 0,
  //     },
  //   },
  // },
];
