import * as React from "react";
import Head from "next/head";
import dynamic from "next/dynamic";
import Link from "next/link";

import { Menu } from "/components/Menu.tsx";

const StartPageItems = [
  { title: "Yahtzee", href: "/yahtzee" },
  { title: "Yahtzee Maxi", href: "/yahtzee" },
  { title: "Gold ScoreCard", href: "/yahtzee" },
  { title: "Other", href: "/yahtzee" },
  { title: "Other", href: "/yahtzee" },
  { title: "Other", href: "/yahtzee" },
];

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link href="http://fonts.cdnfonts.com/css/convergence" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main className="flex w-full min-h-screen bg-slate-800 justify-center pt-8">
        {/* <Yahtzee /> */}
        {/* <GolfScoreCard /> */}
        <div className="grid grid-cols-4 gap-8 w-2/3 h-fit">
          {StartPageItems.map((item) => {
            return (
              <Link href={item.href}>
                <div className="relative bg-slate-700 rounded-lg p-8 border-slate-500 border-2 transition-color duration-300 hover:bg-slate-600 cursor-pointer max-h-96  aspect-square overflow-hidden shadow-xl">
                  <div className="absolute -rotate-45 w-full left-2/3 top-2/3 h-full flex justify-center p-2 bg-gradient-to-l from-cyan-400 via-cyan-300 to-cyan-600 uppercase text-sm">
                    <div>Coming!</div>
                  </div>
                  <h3 className="text-3xl text-white">{item.title}</h3>
                </div>
              </Link>
            );
          })}
        </div>
      </main>
    </div>
  );
}
